## Locators for Chckout Page
checkout_your_information="//span[text()='Checkout: Your Information']"
checkout_page="https://www.saucedemo.com/checkout-step-one.html"
cancel="//button[@id=\'cancel\']"
continue_button="//input[@id=\'continue\']"
error_message_empty_firstname="//h3[text()=\'Error: First Name is required\']"
error_message_empty_lastname="//h3[text()=\'Error: Last Name is required\']"
error_message_empty_zipcode="//h3[text()='Error: Postal Code is required']"
firstname_textbox="//input[@id='first-name']"
lastname_textbox= "//input[@id='last-name']"
zip_textbox= "//input[@id='postal-code']"
finish="//button[@id='finish']"
all_items_page2="https://www.saucedemo.com/inventory.html"
